AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dfpp REPL API (Lambda + HTTP API)

Globals:
  Function:
    Runtime: java21
    MemorySize: 512
    Timeout: 5
    Tracing: Active

Parameters:
  AllowedOrigin:
    Type: String
    Default: https://dfpp.dev
    Description: CORS allowed origin for the REPL API

Resources:
  ReplFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dfpp-repl
      Handler: dfpp.lambda.ReplHandler::handleRequest
      CodeUri: lambda/build/libs
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /run
            Method: POST
            ApiId: !Ref HttpApi

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: false
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins:
          - !Ref AllowedOrigin

Outputs:
  HttpApiUrl:
    Description: API base URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
