name: deploy-backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - 'src/main/java/**'
      - 'src/main/antlr/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build Spring Boot jar
        run: ./gradlew :server:bootJar
      - name: Prepare package
        run: |
          mkdir -p package
          cp server/build/libs/server-*.jar package/app.jar
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: package/app.jar
